# Generated by Django 5.1.3 on 2025-10-13 16:10

import brokers.models.category
import brokers.models.product
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nama Kategori"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=brokers.models.category.upload_category_image,
                        verbose_name="Gambar Kategori",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Misal: fas fa-car, fas fa-motorcycle, dll",
                        max_length=50,
                        verbose_name="Icon CSS Class",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#8b5cf6",
                        help_text="Hex color code",
                        max_length=7,
                        verbose_name="Warna Tema",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Status Aktif"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Kategori Unggulan"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Meta Title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Meta Description"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Urutan"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="brokers.category",
                        verbose_name="Kategori Induk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategori",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Judul Produk"),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Merk/Brand"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Model/Tipe"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "Baru"),
                            ("like_new", "Seperti Baru"),
                            ("good", "Baik"),
                            ("fair", "Cukup Baik"),
                            ("poor", "Perlu Perbaikan"),
                        ],
                        max_length=20,
                        verbose_name="Kondisi",
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Data fleksibel dalam format JSON: {"tahun": "2020", "warna": "Merah", "cc": "150"}',
                        verbose_name="Atribut Produk",
                    ),
                ),
                (
                    "location_city",
                    models.CharField(max_length=100, verbose_name="Kota"),
                ),
                (
                    "location_province",
                    models.CharField(max_length=100, verbose_name="Provinsi"),
                ),
                (
                    "location_detail",
                    models.TextField(blank=True, verbose_name="Alamat Detail"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Harga"
                    ),
                ),
                (
                    "is_negotiable",
                    models.BooleanField(default=True, verbose_name="Bisa Nego"),
                ),
                (
                    "currency",
                    models.CharField(
                        default="IDR", max_length=3, verbose_name="Mata Uang"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=100, verbose_name="Nama Kontak"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="Nomor WhatsApp"),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("description", models.TextField(verbose_name="Deskripsi Produk")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Status Aktif"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Produk Unggulan"),
                ),
                (
                    "is_sold",
                    models.BooleanField(default=False, verbose_name="Sudah Terjual"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Meta Title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Meta Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="brokers.category",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Penjual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produk",
                "verbose_name_plural": "Produk",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=brokers.models.product.upload_product_image,
                        verbose_name="Gambar",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Caption"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Gambar Utama"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Urutan"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="brokers.product",
                        verbose_name="Produk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gambar Produk",
                "verbose_name_plural": "Gambar Produk",
                "ordering": ["order", "-is_main", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inquirer_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nama Penanya"
                    ),
                ),
                (
                    "inquirer_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Nomor HP"
                    ),
                ),
                (
                    "inquirer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Penanya"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Pesan")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Baru"),
                            ("replied", "Sudah Dibalas"),
                            ("closed", "Ditutup"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="brokers.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inquiry Produk",
                "verbose_name_plural": "Inquiry Produk",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="brokers.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "View Produk",
                "verbose_name_plural": "View Produk",
                "unique_together": {("product", "ip_address", "session_key")},
            },
        ),
    ]
