services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        APP_UID: ${APP_UID:-1000}
        APP_GID: ${APP_GID:-1000}
    env_file: .env
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-8000}:8000"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./logs:/app/logs
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG:-False}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-3}
      - GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT:-120}
    user: root
    command: >
      sh -c "
        echo '🧹 Collecting static files...' &&
        python manage.py collectstatic --noinput &&
        echo '🚀 Starting Gunicorn...' &&
        su django -c 'gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers ${GUNICORN_WORKERS:-3} --timeout ${GUNICORN_TIMEOUT:-120}'
      "

        cap_drop: []
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
